### ISSUE TITLE
Unable to query multiple Supermicro systems

### ISSUE THREAD

**Issue by PnoT** [putnam/superfans#1]
Is this script written for a specific motherboard because the only thing it works on is SuperMicro X10 and above boards.

I've tried it against X8, X9, and atom based 2558F boards with no luck.  It either spits back nothing at all and drops me back at the prompt, timesout, or complains about not being root.  If i run the ipmitool -I lanplus against a server with say "sensor list all" the results come back.

**Comment by putnam** [comment]
Hmm, I tested this on an X10 board initially, and used it again on an X11 board since then. I also used it against the IPMI interface on their JBOD management board CSE-PTJBOD-CS3.

As explained in the documentation, if you do not provide a network address / username / password it will try to use ipmitool directly to the kernel module. So that requires root. I wonder if the output from your board is something unexpected...

I just ran it on my X11DPI-NT and it worked fine:

> $ sudo /home/putnam/bin/superfans status
> Preset: Optimal (Temp controlled, target 30%)
> Current fan speed (CPU Zone): 43%
> Current fan speed (Peripheral zone): 43%

I also tried using lanplus and it worked OK, at least on the X11DPI-NT:

> $ superfans -h 192.168.1.144 -u internal -p "mypassword" status
> Preset: Optimal (Temp controlled, target 30%)
> Current fan speed (CPU Zone): 43%
> Current fan speed (Peripheral zone): 43%

I happen to have an older Supermicro server lying around so I'll test with that soon too (it has an X9SCM-F). I should definitely document which generation(s) of boards are supported.

Please provide the command line you're using with superfans so I can tell what you're trying to do. Also please try to run ipmitool with "raw 0x30 0x45 0x00" instead of "sensor list all"; what happens?

**Comment by putnam** [comment]
Added additional compatibility info in the readme with 55c09a6
